version: "3.8"

services:
  app:
    container_name: japanese-company-name-extraction-app
    build: ./app
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    command: uvicorn main:app --reload --host 0.0.0.0
